### ISSUE TITLE
Replaced flynn with custom logo, however the custom logo is getting scrolled and not displayed properly

### ISSUE THREAD

**Issue by arjunharidasp** [chriscareycode/nagiostv-react#11]
Hello,

I was able to place a custom logo/image instead of the flynn.

However the new logo is scrolling every time and not displayed properly due to the difference in the dimensions.

I'm not able to get my logo in a good look with the dimensions of the flynn.

Can you please let me know how to stop the scrolling of the image/logo.

Any help is appreciated.

**Comment by chriscareycode** [comment]
Yeah, that's not going to work since the Flynn image is a "sprite" containing multiple images and not a standard image. I will think about how to add a custom image option.

**Comment by arjunharidasp** [comment]
Hi Chris,

Any update on this??

**Comment by chriscareycode** [comment]
Hi, not yet. I will get this feature in though, probably in the next week or two. I'm working full time so weekends are my only opportunity if life does not get too busy.

**Comment by chriscareycode** [comment]
https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.4.11

**Comment by arjunharidasp** [comment]
Thank  You For bringing in this feature
