### ISSUE TITLE
SOFT and HARD alert

### ISSUE THREAD

**Issue by Nibeck1309** [chriscareycode/nagiostv-react#16]
Hello,

Thank you for your work !!!!!!!

Is it possible to have an option to hide SOFT alerts in history and active alerts in nagiostv?

Best regards

**Comment by arcusbude** [comment]
Hi, i think this is the same request that i opened today ;)
https://github.com/chriscareycode/nagiostv-react/issues/9

**Comment by Nibeck1309** [comment]
Ok, I test the 0.4.11 version, it's good for hide SOFT active alert.
It's possible to have an settings for hide SOFT Alert in history to ?

Regards

**Comment by chriscareycode** [comment]
Yes. I have also been getting a lot of soft alerts lately. Will get some progress on this request to be able to hide soft alerts on History. I'll re-open #9 and put notes there
