### ISSUE TITLE
Move the Alert Section to the top

### ISSUE THREAD

**Issue by nachosavage** [chriscareycode/nagiostv-react#19]
Hello.

How would you go about moving the AlertSection to the top of the page?
Maybe even make so one can pick the position of each section

Thanks in advance!

**Comment by chriscareycode** [comment]
In general, I like the idea of a more configurable layout.

If the Alert History Section was at the top of the page you would never see the Host or Service sections. Did you not want to see those?

I was considering some options like a two column side by side view where you could arrange things in a configurable way. Though at this point its just an idea I would like some input on.

**Comment by nachosavage** [comment]
Thank you for your answer Chris.

It would be interesting to be able choose whats on top so we can have
options for multiple screens (some of them on the small side) for the
agents that have different responsibilities over the monitoring platform.

The configurable two column approach sounds quite good actually. I will
check with my users for input on that.

Best Regards, Ignacio.

**Comment by chriscareycode** [comment]
Ahh. I had not considered the option of having multiple monitors, each displaying different information from a single Nagios server. That is a interesting use case.

**Comment by chriscareycode** [comment]
To keep things simple for now until I get more time, I think I may just add an option to hide or show each section. I'm going to want to refactor the code so that if you hide the Hosts and Services that they do not fetch that data from the server since it is not needed. Though I may release a version before that to just hide them and get to those other optimizations after.

**Comment by chriscareycode** [comment]
I have this feature ready. Just doing some more testing and can probably release it tomorrow

**Comment by chriscareycode** [comment]
@nachosavage I have added this feature into v0.6.0.
You can now hide hosts or services or history visibility in the settings.
Or you can add ?hideHostSection=true and/or ?hideServiceSection=true and/or hideHistory=true on the URL bar to do it without the option in settings. This can allow you to view hosts only, services only, or alerts only in three windows on the same computer. Combine them like `?hideHostSection=true&hideServiceSection=true`

**Comment by nachosavage** [comment]
Excellent news. I'll pass this along to my team so they can implement it.
Thank you for all your help!
