### ISSUE TITLE
New feature to hide ACKED and SCHEDULED items

### ISSUE THREAD

**Issue by karpiozoo** [chriscareycode/nagiostv-react#2]
Hi Chris,
I use nagiosTV for some time and it's realy nice tool to show Nagios status on TV.
But i miss one feature, I would like to hide all checks which are ACKED or Downtimed. When one server is down and I marked it as downtimed, I see on my screen all critical services and I can miss some important Failure when all criticals are mixed (ACKED and Problems).
Can You add one options to settings to disable view of all ACKED and downtimed host/checks ?

**Comment by chriscareycode** [comment]
Sure, this should be an easy change. Thanks for the feature suggestion.

**Comment by chriscareycode** [comment]
I just published a new release with this feature. Please give it a try.
https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.2.4

**Comment by chriscareycode** [comment]
Actually I found a bug related to hiding scheduled items, fixed in https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.2.5

**Comment by karpiozoo** [comment]
Works great, thanks!

pt., 28 gru 2018 o 03:18 użytkownik Chris Carey <notifications@github.com>
napisał:
