### ISSUE TITLE
IE compatibility?

### ISSUE THREAD

**Issue by pezzotto** [chriscareycode/nagiostv-react#21]
Hi, im trying to show nagios tv fron internet explorer but all black, i must use IE cause i need in a xibo cms envoirement.

Any help?

Thanks

**Comment by pezzotto** [comment]
Seems that for Internet Explorer 11 i need to implement [react-app-polyfill](https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md)

I'm not good at all with this implementation, any help?

**Comment by pezzotto** [comment]
Thank you but i think im doing wrong the update.

I run the autoupdate.sh and moved folder from /autoupdate/ to /nagiostv, but with IE11 no luck.

**Comment by chriscareycode** [comment]
Hey @pezzotto  I did not publish a release just yet. I wanted to test the fix on a windows PC then after I verify will cut a release. very soon

**Comment by chriscareycode** [comment]
Published v0.5.5 with IE11 fix

**Comment by pezzotto** [comment]
> Published v0.5.5 with IE11 fix

Working great, thank you!!

**Comment by pezzotto** [comment]
Hi, with the latest 0.5.7 update, nagiostv don't show up again on IE11

**Comment by chriscareycode** [comment]
oops. I'll take a look in a couple hours after waking up and see what caused the break

**Comment by chriscareycode** [comment]
Released v0.5.8 with fix. https://github.com/chriscareycode/nagiostv-react/releases

**Comment by pezzotto** [comment]
Hi, with version 0.6.9 this issue shown again, any fix?

**Comment by chriscareycode** [comment]
Yeah I have repro of the issue. Looks like a bug with core-js or highcharts dependencies. I'll get a fix in after work.

**Comment by chriscareycode** [comment]
@pezzotto  Fix is released v0.7.0 https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.7.0

**Comment by pezzotto** [comment]
> @pezzotto Fix is released v0.7.0 https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.7.0

Thanks for the jet speed reaction.
