### ISSUE TITLE
Feature Requst - Filter by hostgroup

### ISSUE THREAD

**Issue by rcgreenw** [chriscareycode/nagiostv-react#22]
I would like the ability to only show hosts and services on hosts that belong to a specific hostgroup.  This would allow a lobby TV to show only outages that affect a "public" group, and not everything.  It would have to be configurable in the client-settings.json so it could be used by kiosks without interaction.  Thanks.

**Comment by chriscareycode** [comment]
I think this is a good feature to add to the project

**Comment by chriscareycode** [comment]
@rcgreenw Try v0.5.6 https://github.com/chriscareycode/nagiostv-react/releases
You have to click on "Filters" on the bottom menu to show the new option

**Comment by rcgreenw** [comment]
Looks good.  Saving to client-settings.json works.
