### ISSUE TITLE
Remove the NagiosTV from navbottombar

### ISSUE THREAD

**Issue by anexit1** [chriscareycode/nagiostv-react#25]
Just looking for a way to remove the entire bottom bar where the nagiosTV @version sits.

I was able to remove it from the .jsx file in navbottombar.jsx but some reason it doesn't reflect.

Not familiar with react so maybe that is the problem, Cheers!

**Comment by anexit1** [comment]
Never mind, I figured it out!

**Comment by masutomo** [comment]
Hi, I'd like to get it hidden too as it take up too many spaces, any steps to show how to do this? Thanks.

**Comment by chriscareycode** [comment]
I removed some of the bottom bar in release v0.5.9 to expose some more space but will think about how to satisfy users who do not want anything down there. Right now this area has the button to go to settings, and to communicate current version and version update messages. 

Maybe a good compromise would be if I add feature where you add something like ?hideBottomBar=true on the URL to get rid of it for that session.

**Comment by chriscareycode** [comment]
In release 0.6.7 you can now remove the entire bottom bar
