### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by presleyd** [chriscareycode/nagiostv-react#4]
We're big fans here. Thanks for all your work! We'd like to request a feature and I'd be happy to sponsor it if it's not too crazy to do. Could we have an option to play a ding or noise on a new item being added? We made a custom JS to do this using mutationobservers scanning for objects with the 'border-red' or 'border-yellow' classes being added to the dom and playing a wav file for each one. Our TV sits behind our tech bench and they love having the audio alerts. It works fine for our purposes but it's a clugey way to do it. Would you consider adding something similar?

**Comment by chriscareycode** [comment]
Thanks Christian!
I love the idea, this sounds like a lot of fun.
Hopefully can whip something up this weekend.

**Comment by chriscareycode** [comment]
@presleyd Here you go!
https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.3.3

**Comment by presleyd** [comment]
This is awesome! Thanks so much? Do you have a link or place to contribute?

**Comment by chriscareycode** [comment]
That's a kind gesture, but not necessary. Nagios doesn't charge us, at least for their open source offering, so this is my small part in paying it forward.

**Comment by chriscareycode** [comment]
I have a small update ready that will allow multiple sounds for each state that will be chosen at random. It's pretty simple config where you just put a semicolon between the multiple sound URLs to enable it. This feature will drop in 0.3.4
