### ISSUE TITLE
The update menu shows the installed version as 0.7.5 but states the latest version is 0.7.3

### ISSUE THREAD

**Issue by ChrisHird** [chriscareycode/nagiostv-react#45]
from the install done today
Latest version is: v0.7.3
You are running: v0.7.5
You are running a version newer than the latest announced release.

**Comment by ChrisHird** [comment]
Just checked the url to your web site
https://nagiostv.com/version/nagiostv-react/ and can see the version needs to be changed there.

Thanks for the nice work...

**Comment by chriscareycode** [comment]
Yeah I just released a new version a couple days ago but had not updated one of the scripts that announces the latest version. Thanks for the heads up
