### ISSUE TITLE
v0.3.4 stopped working under Fully Kiosk Browser

### ISSUE THREAD

**Issue by ata-sql** [chriscareycode/nagiostv-react#5]
Hello,
we use Odroid devices connected to TVs using HDMI for wallboard in our company.
Changes introduced in v0.3.4 caused or TVs to stay black.
https://github.com/chriscareycode/nagiostv-react/compare/v0.3.3...v0.3.4
I've checked versions 5 and 6 and didn't help.
Kiosk Browser is popular app to show webpage on android devices:
https://play.google.com/store/apps/details?id=de.ozerov.fully

**Comment by chriscareycode** [comment]
Interesting. 0.3.4 added multiple sound support by adding just an extra function. Very small changes there. You are able to run 0.3.3 ok? 

To my understanding odroid is just a more powerful Raspberry Pi. What OS are you running on there? Looks like from your link its running Android? 

I'll dig into this to try to help. Please try to get an error message if you are able.

**Comment by chriscareycode** [comment]
I have about a lot of raspberry pis at home, I wonder if I would be able to repro on one of those?

**Comment by chriscareycode** [comment]
Actually I found the other commit on 0.3.4 which added voices. My suspicion is the error is happening there. Let me add some more checks in those functions which hopefully will help.

**Comment by chriscareycode** [comment]
SpeechSythesisUtterance() not supported on Android Webview
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance

**Comment by chriscareycode** [comment]
@ata-sql 
Try v0.3.7 and let me know if it helps.
https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.3.7

**Comment by ata-sql** [comment]
Hello and thanks for reaction!
Yes, 0.3.3a was latest version, that worked fined. Nice to hear, that you discovered and fixed issue.
I made a change in our infrastructure, but have to wait for acceptance and deploy - I will return with news in couple of hours.

**Comment by ata-sql** [comment]
Works fine, thanks!
