### ISSUE TITLE
Not an issue with TV. Unable to post a discussion thread

### ISSUE THREAD

**Issue by CharlieHird** [chriscareycode/nagiostv-react#50]
I tried to add this under discussions/ideas, however I was unable to?
Anyways,
I was wondering if it would be possible to add a link to the alert history entries, below the graphs, to their respective services in the same manner the current warnings/alerts do? If you do not think there would be any interest for other users I can just change mine!
Thanks,
Charlie

**Comment by chriscareycode** [comment]
Hi Charlie,

Hm, I wonder what needs to be changed on the discussions page to turn that on properly.

Sure, I'll add these links for alert history items. Thanks for the suggestion.
