### ISSUE TITLE
settings cookie should be sorted

### ISSUE THREAD

**Issue by ata-sql** [chriscareycode/nagiostv-react#6]
When new settings are introduced, easiest way to use them is copy cookie from browser and modify client-settings.json file in configuration (we use saltstack).
When settings are not sorted, they sometimes change their order and that makes update of json harder.
![nagiostv-json](https://user-images.githubusercontent.com/15795541/54350024-bdf63980-464c-11e9-83ea-0a7d09d853a8.png)

**Comment by chriscareycode** [comment]
I think I'm understanding your use case but I am hesitant to make this a global change just yet. I do like the settings to be grouped in an order that keeps related options together, and the alphabetical sorting will scramble the related options away from each other. I will have to think more about this one.

**Comment by ata-sql** [comment]
Alphabetical order was just an example. Clue is to avoid reordering like with "versionCheckDays" in my screenshot.
I didn't look into implementation of creating that json - my guess was, that was created from unordered collection, so I suggested alphabetical order. In fact any order will do.

**Comment by chriscareycode** [comment]
One other option is at the very bottom of the settings screen it has the raw JSON. The application will take the default settings, new ones as well, then loads your client-settings.json and will overlay your client-settings over top. So you could just copy that raw JSON and it should be exactly what you need - no need to merge manually.
