### ISSUE TITLE
Update URL for MK Livestatus Writeup

### ISSUE THREAD

**Issue by jordanreedy16** [chriscareycode/nagiostv-react#62]
Hey there,

First I want to say thanks for the shoutout! I've moved my blog so the writeup link is found here now
https://reedy.dev/linux/sysadmin/2022/05/04/NagiosTV-With-Livestatus.html

Instead of https://cyb3rdelic.github.io/2021/01/18/NagiosTV-With-Livesocket.html

I'm going to test out my instructions again since it's been a little while, but hopefully the steps are still functional. I'll update if they're obsolete.
Have a great day!
-Jordan

**Comment by jordanreedy16** [comment]
Made adjustments and confirmed working as of today.

**Comment by chriscareycode** [comment]
Link is updated on the NagiosTV.com website. Thanks so much for that writeup and the work you put into it. It's really fantastic and going to help a lot of people trying to get that installed!
