### ISSUE TITLE
Hide Filters problem

### ISSUE THREAD

**Issue by likeaRAINBOW** [chriscareycode/nagiostv-react#66]
Hey,

if i hide filters, host and services status buttons won't disappear, and i can click on them and filter aswell. Is it a bug? So if i'm click on ACK button on the first pic, it will be showing ACK hosts.
used version 0.8.5
Filter off
<img width="684" alt="Screenshot 2022-10-10 at 15 06 58" src="https://user-images.githubusercontent.com/40559325/194873420-90c0e9da-df34-4013-8328-7feda3abbc9c.png">

Filter on
<img width="1283" alt="Screenshot 2022-10-10 at 15 06 49" src="https://user-images.githubusercontent.com/40559325/194873426-d0ff8913-f141-40f4-a896-f59104206b3a.png">

**Comment by chriscareycode** [comment]
Hi @likeaRAINBOW , this is the intended behavior. When a item is filtered out, the intention is to not have it take any vertical space on the page, but to still be able to know it is there. There will always be the label indicating an item is hidden and how many items are hidden.

I have gone back and forth with "should the label be clickable?" if "Show Filters" is disabled. My preference is to have it clickable for easy access to see what is hidden.
