### ISSUE TITLE
Disable History

### ISSUE THREAD

**Issue by Nibeck1309** [chriscareycode/nagiostv-react#7]
Hello,

How do for disable history and graph ?

Sincerely

**Comment by chriscareycode** [comment]
I will add these options in the settings

**Comment by chriscareycode** [comment]
https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.3.8

**Comment by Nibeck1309** [comment]
Hello,

thanks for your rapid works.

mask graph is perfect.
mask history does not fit what I want.
I would like mask the line 'History: xxx alerts in the past xx day' and the graph
but keep the 'quiet' display.

If it's too complicated to change, if you could just tell me which file to edit to remove 'History : xxx alerts in the past xx day'

Sincerely

**Comment by chriscareycode** [comment]
Only the first "Quiet For", but nothing else?

There are users who would like to disable History completely, where NagiosTV will not fetch history data at all. 

In your request the app will still need to fetch history data to get the quiet for.  Also I feel like without the "History: x alerts in the past y days", and displaying the Quiet For, the Quiet For will be directly under the services with no space and create less visual balance and separation to the page.

**Comment by Nibeck1309** [comment]
hy,

Look this picture, I think you better understand what I want 

[https://image.noelshack.com/fichiers/2019/13/3/1553714576-document-1-page001.png](url)

**Comment by chriscareycode** [comment]
I have to say, it looks very clean like this

**Comment by chriscareycode** [comment]
https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.3.9

**Comment by Nibeck1309** [comment]
hello,

thanks for update

it's exactly that I want.
