### ISSUE TITLE
Add filter by ServiceGroup

### ISSUE THREAD

**Issue by FabFara** [chriscareycode/nagiostv-react#73]
Hi,
it's possible to add the filter by ServiceGroup feauture too?

Thanks

**Comment by zjelcic** [comment]
Hi, I put the same idea in discussions. Hope to have them both.
Hostgroup and servicegroup together.
BR

**Comment by chriscareycode** [comment]
Sure, I will add this feature. Need to set up some service filters on my system to test with.

**Comment by chriscareycode** [comment]
Got service group added. Will go out in the next release.

**Comment by chriscareycode** [comment]
@FabFara @MarcoAngeli @zjelcic : ServiceGroup Filter was added in 0.8.6 that released today. Please try it out and let me know if it works OK for you.

**Comment by zjelcic** [comment]
Thank you for the update. Will give my feedback soon. Thanks again.
Best regards
