### ISSUE TITLE
HostGroup Filter List not populated

### ISSUE THREAD

**Issue by bjhiggins** [chriscareycode/nagiostv-react#75]
I am using NagiosTV to monitor my iCinga instance via LiveStatus and am pulling Host/Service data.  I can confirm that "connectors/livestatus.php?query=hostgrouplist" returns appropriate data for HostGroups and their members.

However, the HostGroup filter pull down is not populated:

![image](https://user-images.githubusercontent.com/3186365/219457308-62fdfc1e-0a9a-43ae-be45-064e50104921.png)

Thoughts on next steps?

**Comment by chriscareycode** [comment]
Never tested with Icinga. It is possible livestatus on Icinga is returning a format slightly different than what the code is expecing. Payload should be like this.
![hostgrouplist](https://user-images.githubusercontent.com/1002638/219902968-6a46086a-56bb-427d-9196-0e18668fb654.png)

Your note made me realize that in the last release where I added "ServiceGroup" filters, that I forgot to update support for ServiceFilters with livestatus. So will get a fix in for that.

Unsure why your HostGroup filters are not showing though. If you could send me a screenshot similar to the one I posted to make sure the payload looks the same.

**Comment by chriscareycode** [comment]
@bjhiggins Please try latest release 0.9.1 and see if it fixes the issue
