### ISSUE TITLE
Handle Large LiveStatus Datasets Better?

### ISSUE THREAD

**Issue by bjhiggins** [chriscareycode/nagiostv-react#76]
I have a large number of Hosts and Services in my iCinga instance.  3394 Hosts and 4957 Services.  When setting up NagiosTV and connectors/livestatus.php - I had to increase my PHP-FPM memory_limit from 256M to 1024M.  

I believe that LiveStatus allows for a "Limit" keyword to return a smaller number of records (https://docs.checkmk.com/latest/en/livestatus.html#_limiting_an_output_limit)

Is there any way to update the connector so that it only requests Hosts/Services which are not in an OK Status rather than all records?  This would shrink the memory requirements of the PHP script and make response time quicker.

**Comment by chriscareycode** [comment]
I like this idea of having the API only return items not in OK status to help the product scale and decrease the CPU on the server.
 
If this is possible then I will just need to find a different way of getting the total # of hosts and total # of services. But that should not be too tough to get with other API calls.

**Comment by chriscareycode** [comment]
This has been added in https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.8.7

**Comment by chriscareycode** [comment]
@bjhiggins Please test out 0.8.7, see how it works and report back
