### ISSUE TITLE
archivejson.cgi does not return values unless endtime is a negative value

### ISSUE THREAD

**Issue by ftigges-comdev** [chriscareycode/nagiostv-react#79]
Nagios Core 4.4.7
NTV: 0.8.7

This could be an error in this Nagios version.

The alertlist is just empty when sending +0.
When sending -0 it works just fine.
When sending +1 as endtime there is an error msg:
"The requested start time must be before the end time."

Which seems odd.

Solution/Workaround: 

In
/usr/share/nagios/nagiostv/static/js/main.5ed0ad9f.js
change endtime entries.

From 
concat(t,"&endtime=%2B

to 

concat(t,"&endtime=%2D 

on both occasions.

Best regards

**Comment by chriscareycode** [comment]
Weird bug. I have the same version of Nagios Core and my archivejson.cgi works fine with +0.  It also works with -0. I wonder what is different with yours and why its unhappy. I will give this change a try in the next release. You are using "cgi bin" mode and not livestatus mode, correct?

**Comment by ftigges-comdev** [comment]
Hi, the Nagios version is shipped with opensuse.

And yes I am using "cgi bin mode".

Thanks for your time  and best regards 

Florian

**Comment by chriscareycode** [comment]
Fix released in 0.9.0. please test and let me know

**Comment by ftigges-comdev** [comment]
v0.9 works like a charm.

Thank you for your efforts
