### ISSUE TITLE
Possible improvment

### ISSUE THREAD

**Issue by SeLLeRoNe** [chriscareycode/nagiostv-react#8]
Hi there,

First of all, thanks!
Thanks for this interface and for your email you sent me to show me this, I know it was long time ago but I completely forgot about this :)

I was trying to implement this and there is something it doesn't work with my setup (Naemon + Livestatus).

This setup required the original .cgi file from Nagios, which I don't have and it is the reason of this "Issue".

It would be, in my personal opinion, much better if you have a way to implement this UI using livestatus or the socket file, this way it would be compatible also with Naemon

As TV UI I am using (at least for now) this one: https://github.com/smarkets/merlin-dashboard

Hope it helps and that you might be interested on doing this change :)

Thanks
Best regards
Andrea

**Comment by BrixSat** [comment]
You could make a php that generates the same json result as nagios.

**Comment by chriscareycode** [comment]
Since I am not running Naemon + Livestatus I don't have a good way to examine that format. This project is tied pretty tightly with the format of the sample data coming from the built-in Nagios cgis @BrixSat posted above. So at this time it is not on the near term roadmap.
