### ISSUE TITLE
Comments not being pulled onto NagiosTV Dash

### ISSUE THREAD

**Issue by WBACC** [chriscareycode/nagiostv-react#82]
Updated from last version to this newest and all comments have disappeared (ive kept all config files the exact same) ive tried removing comments and reapplying them but NagiosTV doesn't seem to acknowledge them.

inspect element shows the commentlist payload being sent and getting a response with the correct data, just not showing on dash on their respective services and hosts.

rollback returns comments, will stick on older version until fixed.

**Comment by chriscareycode** [comment]
Thanks for reporting this. Will test a bit more and get out a fix soon.

**Comment by chriscareycode** [comment]
Hey @WBACC are you fetching data via default Nagios cgi-bin or with MK Livestatus connector?

**Comment by WBACC** [comment]
@chriscareycode through an apache proxy.

**Comment by chriscareycode** [comment]
Released v0.9.1. Please try and let me know.

**Comment by chriscareycode** [comment]
0.9.1 had a bug where the enter and exit animations were broken. Released v0.9.2.

**Comment by WBACC** [comment]
fix looks good to me on 0.9.2, comments are back, thank you chris for the very quick response and fix, only slight issue now is it still reporting 
"Latest version is: v0.8.7 [See what's new in this version at GitHub](https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.8.7)
You are running: v0.9.2"
0.8.7 not being the latest version

**Comment by chriscareycode** [comment]
Glad that is back for you. The latest version mismatch: I like to test new versions with a few users and verify it is working well before bumping the latest version for all users. When I bump latest version it will send notification to all users. To be more clear, in the future I may change that to say something like:
0.9.2 Latest Release
0.8.7 Latest Stable Release
