### ISSUE TITLE
Nagiostv showing 2 services unknown categories

### ISSUE THREAD

**Issue by asylum71** [chriscareycode/nagiostv-react#86]
Hello Chris,

     I installed Nagiostv to my 2 Nagios hosts today and noticed that it has 2 categories showing as services unknown.  I believe the 2nd should be services total like hosts total.  Just installed this today on Nagios 4.5.3 and definitely thanks for the awesomeness!
     
     
<img width="429" alt="image" src="https://github.com/user-attachments/assets/46975af7-b323-4921-836e-85019e352afc">

**Comment by asylum71** [comment]
Fixed the issue.

Log into server

cd /usr/local/nagios/share/nagiostv/assets

cp index-BJDg9LMl.js index-BJDg9LMl.js.BAK

nano index-BJDg9LMl.js

find children:t.howManyServices

change "services",T.jsx("br",{}),"unknown" to "services",T.jsx("br",{}),"total"

Should show up correctly after refreshing the page

<img width="314" alt="image" src="https://github.com/user-attachments/assets/327a4c44-eee9-435e-883f-c83898474510">

**Comment by rmendes-13** [comment]
This error is also present on the main [`README.md`](https://github.com/chriscareycode/nagiostv-react/blob/main/README.md) file on the repo root.

**Comment by chriscareycode** [comment]
Wow I hadn't noticed this typo for a while! Thanks for the heads up!

**Comment by chriscareycode** [comment]
This fix will go out on the next release.

**Comment by asylum71** [comment]
No problem Chris.  😉  Thanks for the awesomeness!!
________________________________
