### ISSUE TITLE
hide soft alerts ?

### ISSUE THREAD

**Issue by arcusbude** [chriscareycode/nagiostv-react#9]
Is there a possibility to hide soft alerts ?

**Comment by chriscareycode** [comment]
Good idea! I've got most of this done. Just putting a few finishing touches and some more testing and this will go out with next version 0.4.7

**Comment by chriscareycode** [comment]
This is released in 0.4.7. Please test it out.

**Comment by arcusbude** [comment]
Hello Chris,

sorry for my late reply. But i have a new job and iam in the beginning auf climbing on a big big rock ;)

Have tested your release, and yes this is near of this what i feel an admin need (or a devop or what ever)

the soft alerts are in my opinion, something we need to get a feeling of the quality of my service. but we all know this situations were we want only to see REAL problems.. the history below the service states still contains all alerts unfiltered. maybe a checkbox "apply filter also on history would be nice"

did you also think this make sense ? 

would be great to here your opinion.

**Comment by chriscareycode** [comment]
Yes, will also get a filter in for History

**Comment by chriscareycode** [comment]
@arcusbude  can you give v0.5.0 a try and let me know
https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.5.0

**Comment by arcusbude** [comment]
Hello Chris,

Erverything works as expected. Thanks for this.

But a little question. after swap the nagios tv with the extracted targz and copying the client-settings.json from the original i get sample data in my nagiostv ? ;)
whats going wrong there ?

Greetings Robert

Chris Carey schrieb am 22.04.2020 04:17 (GMT +02:00):

**Comment by Nibeck1309** [comment]
Hello,
Same issue for me too

**Comment by chriscareycode** [comment]
@arcusbude @Nibeck1309 Sorry about that!! I must have been tired and left the sample data on. I use that during development to help test things...

Released 0.5.1 with that fixed
https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.5.1

**Comment by chriscareycode** [comment]
Filters button has moved to the left bar as one of those new icons.
So you will need to highlight the filters option to show filters, then you should see "SOFT" filter down in the alerts area. I will add some more filters for alerts over time. Just starting with SOFT for now.

**Comment by chriscareycode** [comment]
![Screen Shot 2020-04-22 at 8 36 05 AM](https://user-images.githubusercontent.com/1002638/80002356-61329880-8474-11ea-8ab2-3c2c91b75c39.png)

**Comment by Nibeck1309** [comment]
Thanks for your works.

It's good for me

But i open new future demand for hide sidebar :D
